
package com.leavemanagementsystem.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.1
 * Wed Apr 06 01:04:21 IST 2016
 * Generated source version: 3.1.1
 */

@XmlRootElement(name = "generateStudentId", namespace = "http://service.leavemanagementsystem.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "generateStudentId", namespace = "http://service.leavemanagementsystem.com/", propOrder = {"arg0", "arg1"})

public class GenerateStudentId {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;
    @XmlElement(name = "arg1")
    private java.sql.Date arg1;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

    public java.sql.Date getArg1() {
        return this.arg1;
    }

    public void setArg1(java.sql.Date newArg1)  {
        this.arg1 = newArg1;
    }

}

