
package com.leavemanagementsystem.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.1
 * Wed Apr 06 01:44:57 IST 2016
 * Generated source version: 3.1.1
 */

@XmlRootElement(name = "getName", namespace = "http://service.leavemanagementsystem.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getName", namespace = "http://service.leavemanagementsystem.com/")

public class GetName {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

