
package com.leavemanagementsystem.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.1
 * Wed Apr 06 01:44:57 IST 2016
 * Generated source version: 3.1.1
 */

@XmlRootElement(name = "getNameResponse", namespace = "http://service.leavemanagementsystem.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getNameResponse", namespace = "http://service.leavemanagementsystem.com/")

public class GetNameResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

